/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApotekRouteImport } from './routes/apotek'
import { Route as ClinicRouteImport } from './routes/clinic'
import { Route as ManajemenProyekRouteImport } from './routes/manajemen-proyek'
import { Route as ManufactureRouteImport } from './routes/manufacture'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as SchoolAcademicRouteImport } from './routes/school-academic'
import { Route as SchoolHrRouteImport } from './routes/school-hr'
import { Route as TahfidzRouteImport } from './routes/tahfidz'
import { Route as UmrohRouteImport } from './routes/umroh'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as YayasanRouteImport } from './routes/yayasan'
import { Route as IndustryLandingRouteImport } from './routes/$industry/landing'
import { Route as LoginIndustryIdRouteImport } from './routes/login.$industryId'
import { Route as IndustryMenuMenuRouteImport } from './routes/$industry/menu.$menu'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApotekRoute = ApotekRouteImport.update({
  id: '/apotek',
  path: '/apotek',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicRoute = ClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const ManajemenProyekRoute = ManajemenProyekRouteImport.update({
  id: '/manajemen-proyek',
  path: '/manajemen-proyek',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufactureRoute = ManufactureRouteImport.update({
  id: '/manufacture',
  path: '/manufacture',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolAcademicRoute = SchoolAcademicRouteImport.update({
  id: '/school-academic',
  path: '/school-academic',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolHrRoute = SchoolHrRouteImport.update({
  id: '/school-hr',
  path: '/school-hr',
  getParentRoute: () => rootRouteImport,
} as any)
const TahfidzRoute = TahfidzRouteImport.update({
  id: '/tahfidz',
  path: '/tahfidz',
  getParentRoute: () => rootRouteImport,
} as any)
const UmrohRoute = UmrohRouteImport.update({
  id: '/umroh',
  path: '/umroh',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const YayasanRoute = YayasanRouteImport.update({
  id: '/yayasan',
  path: '/yayasan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryLandingRoute = IndustryLandingRouteImport.update({
  id: '/$industry/landing',
  path: '/$industry/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndustryIdRoute = LoginIndustryIdRouteImport.update({
  id: '/login/$industryId',
  path: '/login/$industryId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustryMenuMenuRoute = IndustryMenuMenuRouteImport.update({
  id: '/$industry/menu/$menu',
  path: '/$industry/menu/$menu',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apotek': typeof ApotekRoute
  '/clinic': typeof ClinicRoute
  '/manajemen-proyek': typeof ManajemenProyekRoute
  '/manufacture': typeof ManufactureRoute
  '/office': typeof OfficeRoute
  '/restaurant': typeof RestaurantRoute
  '/school-academic': typeof SchoolAcademicRoute
  '/school-hr': typeof SchoolHrRoute
  '/tahfidz': typeof TahfidzRoute
  '/umroh': typeof UmrohRoute
  '/warehouse': typeof WarehouseRoute
  '/yayasan': typeof YayasanRoute
  '/$industry/landing': typeof IndustryLandingRoute
  '/login/$industryId': typeof LoginIndustryIdRoute
  '/$industry/menu/$menu': typeof IndustryMenuMenuRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apotek': typeof ApotekRoute
  '/clinic': typeof ClinicRoute
  '/manajemen-proyek': typeof ManajemenProyekRoute
  '/manufacture': typeof ManufactureRoute
  '/office': typeof OfficeRoute
  '/restaurant': typeof RestaurantRoute
  '/school-academic': typeof SchoolAcademicRoute
  '/school-hr': typeof SchoolHrRoute
  '/tahfidz': typeof TahfidzRoute
  '/umroh': typeof UmrohRoute
  '/warehouse': typeof WarehouseRoute
  '/yayasan': typeof YayasanRoute
  '/$industry/landing': typeof IndustryLandingRoute
  '/login/$industryId': typeof LoginIndustryIdRoute
  '/$industry/menu/$menu': typeof IndustryMenuMenuRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apotek': typeof ApotekRoute
  '/clinic': typeof ClinicRoute
  '/manajemen-proyek': typeof ManajemenProyekRoute
  '/manufacture': typeof ManufactureRoute
  '/office': typeof OfficeRoute
  '/restaurant': typeof RestaurantRoute
  '/school-academic': typeof SchoolAcademicRoute
  '/school-hr': typeof SchoolHrRoute
  '/tahfidz': typeof TahfidzRoute
  '/umroh': typeof UmrohRoute
  '/warehouse': typeof WarehouseRoute
  '/yayasan': typeof YayasanRoute
  '/$industry/landing': typeof IndustryLandingRoute
  '/login/$industryId': typeof LoginIndustryIdRoute
  '/$industry/menu/$menu': typeof IndustryMenuMenuRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apotek'
    | '/clinic'
    | '/manajemen-proyek'
    | '/manufacture'
    | '/office'
    | '/restaurant'
    | '/school-academic'
    | '/school-hr'
    | '/tahfidz'
    | '/umroh'
    | '/warehouse'
    | '/yayasan'
    | '/$industry/landing'
    | '/login/$industryId'
    | '/$industry/menu/$menu'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apotek'
    | '/clinic'
    | '/manajemen-proyek'
    | '/manufacture'
    | '/office'
    | '/restaurant'
    | '/school-academic'
    | '/school-hr'
    | '/tahfidz'
    | '/umroh'
    | '/warehouse'
    | '/yayasan'
    | '/$industry/landing'
    | '/login/$industryId'
    | '/$industry/menu/$menu'
  id:
    | '__root__'
    | '/'
    | '/apotek'
    | '/clinic'
    | '/manajemen-proyek'
    | '/manufacture'
    | '/office'
    | '/restaurant'
    | '/school-academic'
    | '/school-hr'
    | '/tahfidz'
    | '/umroh'
    | '/warehouse'
    | '/yayasan'
    | '/$industry/landing'
    | '/login/$industryId'
    | '/$industry/menu/$menu'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApotekRoute: typeof ApotekRoute
  ClinicRoute: typeof ClinicRoute
  ManajemenProyekRoute: typeof ManajemenProyekRoute
  ManufactureRoute: typeof ManufactureRoute
  OfficeRoute: typeof OfficeRoute
  RestaurantRoute: typeof RestaurantRoute
  SchoolAcademicRoute: typeof SchoolAcademicRoute
  SchoolHrRoute: typeof SchoolHrRoute
  TahfidzRoute: typeof TahfidzRoute
  UmrohRoute: typeof UmrohRoute
  WarehouseRoute: typeof WarehouseRoute
  YayasanRoute: typeof YayasanRoute
  IndustryLandingRoute: typeof IndustryLandingRoute
  LoginIndustryIdRoute: typeof LoginIndustryIdRoute
  IndustryMenuMenuRoute: typeof IndustryMenuMenuRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apotek': {
      id: '/apotek'
      path: '/apotek'
      fullPath: '/apotek'
      preLoaderRoute: typeof ApotekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic': {
      id: '/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof ClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manajemen-proyek': {
      id: '/manajemen-proyek'
      path: '/manajemen-proyek'
      fullPath: '/manajemen-proyek'
      preLoaderRoute: typeof ManajemenProyekRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacture': {
      id: '/manufacture'
      path: '/manufacture'
      fullPath: '/manufacture'
      preLoaderRoute: typeof ManufactureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-academic': {
      id: '/school-academic'
      path: '/school-academic'
      fullPath: '/school-academic'
      preLoaderRoute: typeof SchoolAcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-hr': {
      id: '/school-hr'
      path: '/school-hr'
      fullPath: '/school-hr'
      preLoaderRoute: typeof SchoolHrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tahfidz': {
      id: '/tahfidz'
      path: '/tahfidz'
      fullPath: '/tahfidz'
      preLoaderRoute: typeof TahfidzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/umroh': {
      id: '/umroh'
      path: '/umroh'
      fullPath: '/umroh'
      preLoaderRoute: typeof UmrohRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yayasan': {
      id: '/yayasan'
      path: '/yayasan'
      fullPath: '/yayasan'
      preLoaderRoute: typeof YayasanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$industry/landing': {
      id: '/$industry/landing'
      path: '/$industry/landing'
      fullPath: '/$industry/landing'
      preLoaderRoute: typeof IndustryLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$industryId': {
      id: '/login/$industryId'
      path: '/login/$industryId'
      fullPath: '/login/$industryId'
      preLoaderRoute: typeof LoginIndustryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$industry/menu/$menu': {
      id: '/$industry/menu/$menu'
      path: '/$industry/menu/$menu'
      fullPath: '/$industry/menu/$menu'
      preLoaderRoute: typeof IndustryMenuMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApotekRoute: ApotekRoute,
  ClinicRoute: ClinicRoute,
  ManajemenProyekRoute: ManajemenProyekRoute,
  ManufactureRoute: ManufactureRoute,
  OfficeRoute: OfficeRoute,
  RestaurantRoute: RestaurantRoute,
  SchoolAcademicRoute: SchoolAcademicRoute,
  SchoolHrRoute: SchoolHrRoute,
  TahfidzRoute: TahfidzRoute,
  UmrohRoute: UmrohRoute,
  WarehouseRoute: WarehouseRoute,
  YayasanRoute: YayasanRoute,
  IndustryLandingRoute: IndustryLandingRoute,
  LoginIndustryIdRoute: LoginIndustryIdRoute,
  IndustryMenuMenuRoute: IndustryMenuMenuRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
